version: '3.2'
services:

  smart-launcher: # SMART Launcher ---------------------------------------------
    image: smartonfhir/smart-launcher
    environment:
      NODE_ENV               : "production"
      LAUNCHER_BASE_URL      : "http://localhost:${LAUNCHER_PORT}"
      BASE_URL               : "http://localhost:${LAUNCHER_PORT}"
      FHIR_SERVER_R2         : "http://localhost:${HAPI_PORT_STU2}/baseDstu2"
      FHIR_SERVER_R3         : "http://localhost:${HAPI_PORT_STU3}/baseDstu3"
      FHIR_SERVER_R2_INTERNAL: "http://stu2:8080/baseDstu2"
      FHIR_SERVER_R3_INTERNAL: "http://stu3:8080/baseDstu3"
      DISABLE_SANDBOXES      : "1"
      CDS_SANDBOX_URL        : "https://sandbox.cds-hooks.org"
      PICKER_CONFIG_R2       : "dstu2-local"
      PICKER_CONFIG_R3       : "stu3-local"
      PICKER_ORIGIN          : "http://localhost:${PATIENT_BROWSER_PORT}"

    ports:
      - "${LAUNCHER_PORT}:80"
    depends_on:
      - patient-browser
      - fhir-viewer
      - stu3
      - stu2

  stu3: # HAPI STU3 ------------------------------------------------------------
    image: smartonfhir/hapi:r3
    ports:
      - "${HAPI_PORT_STU3}:8080"

  stu2: # HAPI STU2 ------------------------------------------------------------
    image: smartonfhir/hapi:r2
    ports:
      - "${HAPI_PORT_STU2}:8080"

  patient-browser: # Patient Browser -------------------------------------------
    image: smartonfhir/patient-browser
    ports:
      - "${PATIENT_BROWSER_PORT}:80"
    volumes:
      - type: bind
        source: ./patient-browser
        target: /usr/share/nginx/html/config
  
  fhir-viewer: # Fhir Viewer ---------------------------------------------------
    image: smartonfhir/fhir-viewer
    ports:
      - "${FHIR_VIEWER_PORT}:80"

  index: # Index page ----------------------------------------------------------
    image: nginx:alpine
    ports:
      - "${CONTROL_PANEL_PORT}:80"
    volumes:
      - type: bind
        source: ./www
        target: /usr/share/nginx/html

  